name: Minecraft Mod Derleme

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Java Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Uyumlu Gradle Sistemini Kur
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '7.6' # ForgeGradle 5.1 ile tamamen uyumlu çalışan sürüm
        
    - name: Modu Derle (Build)
      run: gradle build
      
    - name: Mod Dosyasını (JAR) Yayınla
      uses: actions/upload-artifact@v4
      with:
        name: Hazir-Minecraft-Modu
        path: build/libs/*.jar
