name: Minecraft Mod Derleme

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Java Kurulumu (Java 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Temiz Gradle Kurulumu
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '7.6'

    - name: Bağımlılıkları Önceden Hazırla
      run: gradle dependencies --no-daemon

    - name: Modu Derle (Build)
      run: gradle build --no-daemon -x test
      
    - name: Mod Dosyasını (JAR) Yayınla
      uses: actions/upload-artifact@v4
      with:
        name: Hazir-Minecraft-Modu
        path: build/libs/*.jar
